### ISSUE TITLE
Comparing LLM performance on context based question answering

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#150]
## Description
Explore alternative models that are simpler than GPT 3.5 for context-based question answering and assess their suitability for the task.

## Goals
- [ ] Research and identify simpler models that can be used for context-based question answering
- [ ] Evaluate the performance and capabilities of the identified models
- [ ] Determine the feasibility of using simpler models as an alternative to GPT 3.5 for the given task

## Expected Outcome
By exploring simpler models for context-based question answering, you can identify alternatives that may be more lightweight and efficient compared to GPT 3.5. This evaluation will help determine the feasibility of using simpler models while still achieving satisfactory performance in answering questions based on provided context.

## Acceptance Criteria
- [ ] Research is conducted to identify simpler models suitable for context-based question answering
- [ ] The performance and capabilities of the identified models are evaluated
- [ ] A comparison is made between GPT 3.5 and the simpler models in terms of suitability for the given task

## Mockups / Wireframes
[N/A]

---

### Project
AI-tools

### Organization Name:
Samagra

### Product Name
AmakrusAI

### Domain
Social Welfare

### Tech Skills Needed:
Machine Learning, Natural Language Processing, Python

### Mentor(s)
@ChakshuGautam

### Complexity
Medium

### Category
Machine Learning

### Sub Category
Model Evaluation

**Comment by vibhu2408** [comment]
I came across a project called "AmakrusAI" under the organization "Samagra" in the domain of social welfare. The project focuses on exploring alternative models for context-based question answering, with the goal of identifying simpler models that can be used as an alternative to GPT 3.5. I find this project intriguing and would like to work on it.

My background includes expertise in machine learning and natural language processing, which I believe are relevant skills for this project. I have experience with Python, which is listed as a required tech skill. I am eager to research and evaluate simpler models suitable for context-based question answering, comparing them to the performance and capabilities of GPT 3.5.

I believe that working on this project will provide me with valuable insights into alternative models and their feasibility in real-world applications. I am excited to contribute to the social welfare domain by developing AmakrusAI.

**Comment by Gautam-Rajeev** [comment]
Yes, the idea behind this is to move from chatGPT to other LLMs that we can set up on our servers. 
Our use case is mostly around being to be answer a question based on some given context. We need to identify other LLM, (these can be big LLMs that are  (almost) as powerful as Gpt and expensive to deploy)  like Falcon to simpler just summarization models like Squad-BART. 
We need to identify such question and create our own 'leaderboard' for answers to these questions.

**Comment by vibhu2408** [comment]
Thank you for providing further details about the project and the objective of exploring alternative language models (LLMs) for context-based question answering. I understand that the aim is to transition from GPT-3.5 to other LLMs that can be deployed on Samagra's servers.

Given the use case of answering questions based on provided context, we can consider a range of LLMs that vary in complexity and cost. Here are a few options we can explore:

1. Falcon: Falcon is a powerful LLM that can be an alternative to GPT-3.5. While it may be expensive to deploy, it offers comparable performance and capabilities, making it a viable candidate for our needs.

2. Squad-BART: If we are looking for simpler summarization models, Squad-BART can be a good choice. It focuses on question answering and summarization tasks, which align with our requirements. Squad-BART is generally less computationally expensive compared to larger LLMs like GPT-3.5 or Falcon.

To identify the best LLMs for our context-based question answering task, we can conduct a thorough evaluation. Here is an outline of the evaluation process:

1. Research and identify potential LLMs: Explore different LLMs that are suitable for context-based question answering. Consider factors such as model architecture, performance on benchmark datasets, and ease of deployment.

2. Evaluate performance and capabilities: Compare the identified LLMs in terms of their performance and capabilities. Measure metrics such as accuracy, speed, and resource requirements to assess their suitability for our use case.

3. Cost analysis: Consider the cost implications of deploying each LLM. Evaluate factors such as model size, inference time, and computational resources required to determine the most cost-effective option.

4. Create a leaderboard: Develop a customized leaderboard to rank the performance of the identified LLMs. This will help us track and compare their performance on specific questions and contexts.

By following this evaluation process, we can make an informed decision about the most suitable LLMs for our context-based question answering task. I'm excited to work on this project and contribute to the development of AmakrusAI.

**Comment by Maatrika-P** [comment]
Can you give me some more description, so i too can start helping you out regarding this.

**Comment by vibhu2408** [comment]
Thank you for your willingness to contribute to the project!

The project "AmakrusAI" aims to explore alternative models for context-based question answering. Currently, the project utilizes GPT-3.5, but the goal is to identify simpler models that can be used as alternatives. The motivation behind this exploration is to find models that are more lightweight and efficient while still achieving satisfactory performance in answering questions based on provided context.

As a team, we will conduct research to identify simpler models suitable for context-based question answering. This research will involve exploring various language models and considering factors such as model architecture, performance on benchmark datasets, ease of deployment, and cost implications. We will also evaluate the performance and capabilities of the identified models and compare them to GPT-3.5.

The ultimate objective is to determine the feasibility of using simpler models as an alternative to GPT-3.5 for the given task. This assessment will be based on the performance metrics, computational resources required, and cost considerations of the identified models.

Your role in the project will be to collaborate with the team in researching and evaluating these simpler models. You can contribute by conducting literature reviews, experimenting with different models, evaluating their performance, and helping create a leaderboard to track their performance on specific questions and contexts.

**Comment by vibhu2408** [comment]
> Can you give me some more description, so i too can start helping you out regarding this.

Thank you for your willingness to contribute to the project!

The project "AmakrusAI" aims to explore alternative models for context-based question answering. Currently, the project utilizes GPT-3.5, but the goal is to identify simpler models that can be used as alternatives. The motivation behind this exploration is to find models that are more lightweight and efficient while still achieving satisfactory performance in answering questions based on provided context.

As a team, we will conduct research to identify simpler models suitable for context-based question answering. This research will involve exploring various language models and considering factors such as model architecture, performance on benchmark datasets, ease of deployment, and cost implications. We will also evaluate the performance and capabilities of the identified models and compare them to GPT-3.5.

The ultimate objective is to determine the feasibility of using simpler models as an alternative to GPT-3.5 for the given task. This assessment will be based on the performance metrics, computational resources required, and cost considerations of the identified models.

Your role in the project will be to collaborate with the team in researching and evaluating these simpler models. You can contribute by conducting literature reviews, experimenting with different models, evaluating their performance, and helping create a leaderboard to track their performance on specific questions and contexts.

**Comment by shephinphilip** [comment]
Hi  @GautamR-Samagra ,

I'm excited to see that you're working on a project to explore simpler models for context-based question answering. I've been working on this problem myself, and I've identified a few simpler models that I think could be promising.

DistilBERT: This is a smaller, lighter version of BERT that is still very effective at question answering. It is much faster to train and deploy than GPT-3.5, and it can be used on devices with limited resources.

RoBERTa: This is a newer model that is based on BERT but has been fine-tuned on a larger dataset of text and code. It is slightly more complex than DistilBERT, but it has been shown to achieve better performance on some question answering tasks.

T5: This model is designed for text-to-text transfer learning, which means that it can be used for a variety of tasks, including question answering. It is not as specialized as BERT or RoBERTa, but it can be used to achieve good performance on a variety of question answering datasets.

XLNet: This model is based on the Transformer architecture, which is the same architecture used by BERT and RoBERTa. It is slightly more complex than these models, but it has been shown to achieve better performance on some question answering tasks.

I'm happy to contribute to the project by conducting literature reviews, experimenting with different models, evaluating their performance, and helping create a leaderboard to track their performance on specific questions and contexts.

Please let me know if you have any questions. I'm eager to get started!

**Comment by Gautam-Rajeev** [comment]
Thanks everyone, yes the idea is correct. We only want to consider models that we can deploy in our systems (unlike openai models). 
It needs to solve for this particular use case though where there are 2 elements :
- A question posed by user 
- Content found by a retriever 

We need to be abe to answer the question based on the retreived content but also answer in details. (for example. Sqaud-BART is usually trained to just extract the answer but not provide much details)

@H4R5H1T-007  can you add some examples here of expected Q-Content-Answer combinations?

**Comment by H4R5H1T-007** [comment]
Here are some example question answer from given context.
Paragraph 1:
Perfect leveling is crucial for the successful cultivation of the paddy crop. The Soil and Plant Nutrition Farmer's Handbook on Basic Agriculture provides a range of soil pH levels from strongly acidic to strongly alkaline (4.0 to 10). It also emphasizes the importance of nitrogen, phosphorus, potassium, sulfur, calcium, magnesium, iron, manganese, boron, copper, zinc, and molybdenum as essential nutrients for crop growth. Legumes are particularly valuable in agriculture due to their high nitrogen content and low Carbon-Nitrogen Ratio (C:N Ratio), which makes them highly desirable for cultivation.

Question 1 (from Paragraph 1):
What are the essential nutrients mentioned in the Soil and Plant Nutrition Farmer's Handbook for crop growth, and why are legumes considered highly desirable for cultivation based on their nitrogen content and Carbon-Nitrogen Ratio (C:N Ratio)?

Answer 1:
The essential nutrients mentioned in the handbook are nitrogen, phosphorus, potassium, sulfur, calcium, magnesium, iron, manganese, boron, copper, zinc, and molybdenum. Legumes are highly desirable for cultivation due to their high nitrogen content and low C:N Ratio, making them valuable for promoting crop growth.

Paragraph 2:
In agricultural practices, various techniques contribute to successful crop cultivation and soil health. These include applying organic manures, mulching organic wastes, using green manures and cover crops, implementing suitable crop rotation, reducing soil tillage, and preventing soil erosion. The Carbon-Nitrogen Ratio (C:N Ratio) is an essential factor in organic matter decomposition, with a balanced ratio promoting effective breakdown. For example, legumes with a low C:N Ratio, like composted manure (20:1), are highly desirable for their nitrogen content. Farmers can enhance decomposition by using nitrogen-rich organic materials such as blood meal, bone meal, poultry manure, cottonseed meal, and soybean meal. Additionally, Electrical Conductivity (EC) measurement helps address saline/sodic soils through gypsum application, determined by the EC value. Soil testing and expert guidance are recommended for farmers facing such soil issues.

Question 2 (from Paragraph 2):
What agricultural practices contribute to successful crop cultivation and soil health, and how does the Carbon-Nitrogen Ratio (C:N Ratio) impact organic matter decomposition? Provide examples of nitrogen-rich organic materials that can enhance decomposition.

Answer 2:
Agricultural practices such as applying organic manures, mulching organic wastes, using green manures and cover crops, implementing suitable crop rotation, reducing soil tillage, and preventing soil erosion are essential for successful crop cultivation and soil health. The C:N Ratio plays a significant role in organic matter decomposition, and a balanced ratio facilitates effective breakdown. For example, nitrogen-rich organic materials like blood meal, bone meal, poultry manure, cottonseed meal, and soybean meal enhance decomposition.

Paragraph 3:
Deficiency symptoms of essential nutrients in plants can significantly impact crop health and productivity. For nitrogen deficiency, symptoms include stunted growth, light green to pale-yellow color on older leaves, reduced flowering, and lower protein content. Phosphorus deficiency leads to an overall stunted appearance, dark to blue-green coloration in mature leaves, restricted root development, occasional purpling of leaves and stems, and delayed maturity with poor seed and fruit development. Potassium deficiency manifests as chlorosis along leaf margins, scorching and browning of older leaf tips, slow and stunted plant growth, weak stalks leading to lodging, and shriveled seeds or fruits. Calcium deficiencies, while not commonly seen in the field due to secondary effects of high acidity, can affect young leaves of new plants, causing distortion, small and abnormally dark green appearance, cup-shaped and crinkled leaves, and deterioration of terminal buds with root growth impairment.

Question 3 (from Paragraph 3):
What are the deficiency symptoms of nitrogen, phosphorus, potassium, and calcium in plants, and how do these symptoms affect crop health? Explain the reason why calcium deficiencies are not commonly observed in the field.

Answer 3:
The deficiency symptoms of nitrogen include stunted growth, pale-yellow color on older leaves, reduced flowering, and lower protein content. Phosphorus deficiency leads to an overall stunted appearance, dark to blue-green coloration in mature leaves, restricted root development, occasional purpling of leaves and stems, and delayed maturity with poor seed and fruit development. Potassium deficiency manifests as chlorosis along leaf margins, scorching and browning of older leaf tips, slow and stunted plant growth, weak stalks leading to lodging, and shriveled seeds or fruits. Calcium deficiencies are not commonly seen in the field due to secondary effects of high acidity, which limits growth and masks the typical symptoms.

**Comment by SoumyadipYT-OSS** [comment]
I came across this project under the organization "Samagra" in the domain of social welfare. The project focuses on exploring alternative models for context-based question answering, with the goal of identifying simpler models that can be used as an alternative to GPT 3.5. I find this project intriguing and would like to work on it.

My background includes good understanding in machine learning and basic knowledge in natural language processing, which I believe are relevant skills for this project. I have intermediate knowledge in Python, which is listed as a required tech skill. I am eager to research and evaluate simpler models suitable for context-based question answering, comparing them to the performance and capabilities of GPT 3.5.

I believe that working on this project will provide me with valuable insights into alternative models and their feasibility in real-world applications.
