### ISSUE TITLE
Link Odia KenLM Model to Fairseq STT MMS Model

### ISSUE THREAD

**Issue by Gautam-Rajeev** [Samagra-Development/ai-tools#211]
### Description:
Currently, we are facing difficulties in integrating an Odia KenLM model with the Fairseq STT (Speech-to-Text) MMS (Multimodal Model Server) model. The objective is to enhance the performance of the MMS model by incorporating a language decoder model that performs beam search over text outputs and selects the correct word. Without the LM model, the MMS model returns words with significant spelling mistakes. To address this issue, we have attempted to create a KenLM model and a lexicon file, and then integrate them with the Fairseq model using a separate collab file.

Collab to create KenLM model and Lexicon file:  
https://colab.research.google.com/drive/102yFuOZkzQoCr4VpVaD7Te-cUgW0Zmwf?usp=sharing

Collab to link the KenLM model with the Fairseq model: 
https://colab.research.google.com/drive/1PLiiNnDDPZvRvtqwfYHxN8RfD5s0IXqH?usp=sharing

Steps to follow:

- Run both the collabs and replicate the restults.  You may need to attach your drive to it and need to copy the .bin file and the lexicon.txt file to use in the other collab
- Observe that the Odia model does not work as expected with the created KenLM models and lexicon files, unlike the English KenLM models downloaded from external sources.
- Test with an English.txt file to create our own kenlm.bin file and lexicon.txt file for English and check if the Fairseq model works with the created English kenlm model
- I think the issue is with the lexicon file. Modify the lexicon file based on errors to make it work.
- Figure out code changes required to create a correct KenLM file and Lexicon.txt file to make the setup functional

### Expected Behavior:
The Odia KenLM model should integrate seamlessly with the fairseq STT MMS model, improving its performance by reducing spelling errors in text outputs.

### Goals:

Research and investigate the compatibility of Odia KenLM models with the Fairseq STT MMS model.
Identify and resolve any potential issues hindering the integration of the Odia KenLM model.

### Acceptance Criteria:

The Odia KenLM model is successfully integrated with the fairseq STT MMS model.

### Implementation Details:
The issue involves modifications to the collab files responsible for creating the KenLM model and integrating it with the fairseq MMS model. The primary programming languages involved are Python for implementing the machine learning models and natural language processing techniques.

### Mockups/Wireframes:
[N/A]

### Project: 
AI-tools

### Organization Name: 
Samagra

### Product Name:
 AmakrusAI

### Domain: 
Speech to Text

### Tech Skills Needed:

Machine Learning
Natural Language Processing
Python

### Mentor(s): 
 @GautamR-Samagra 

### Complexity: 
Medium

### Category:
Machine Learning, [PoC]

Files if required for testing:  
[lexicon_test.txt](https://github.com/Samagra-Development/ai-tools/files/12121965/lexicon_test.txt)
5gram.bin file : https://drive.google.com/file/d/13rC-Hnqj6LM-x_yWIBJtE9gDjnUUHti9/view?usp=drive_link

Audio :
Odia audio (anorexia prevention) :https://drive.google.com/file/d/1SHdH5hpPIV7W32ng9LKeaJ8aponnlZXQ/view?usp=sharing

English audio (male) :  https://drive.google.com/file/d/1K7XVq7B4vMshQdwGxCyogATLqxguvKUR/view?usp=drive_link

**Comment by Jiya126** [comment]
I tried making bin and lexicon files for English, but getting same assertion errors on that too.
So, the problem is with lexicon files or maybe the decoding hyperparameters.

I used small dataset just to observe the error.
Here are the training txt, bin, lexicon file for same. These files are generated using the same colab file, mentioned above in issue.
https://drive.google.com/drive/folders/1WF5ibmw4f7Awu-Xpp-XusPB_OXfN5ErS?usp=sharing

```
#using kenLM and MMS on english
%%time
decoding_cmds = """
decoding.type=kenlm
decoding.beam=500
decoding.beamsizetoken=50
decoding.lmweight=2.69
decoding.wordscore=2.8
decoding.lmpath=/content/5gram_test_eng.bin
decoding.lexicon=/content/lexicon_eng.txt
""".replace("\n", " ")
!python examples/mms/asr/infer/mms_infer.py --model "/content/fairseq/models_new/mms1b_fl102.pt" --lang "eng" --audio '/content/male16.wav' \
    --extra-infer-args '{decoding_cmds}'

```

This is the last cell code to integrate both models for transcribing audio files

**Comment by Gautam-Rajeev** [comment]
@Jiya126 Great work so far! Can we try and figure out which one is the issue. It should be the lexicon files. 
Can we somehow confirm that ?

**Comment by Jiya126** [comment]
> @Jiya126 Great work so far! Can we try and figure out which one is the issue. It should be the lexicon files. Can we somehow confirm that ?

As per the assertion errors being displayed, it seems like the lexicon file issue.
Since I tried commenting out the 
```
assert (
                        tgt_dict.unk() not in spelling_idxs
                    ), f"{word} {spelling} {spelling_idxs}"
                    self.trie.insert(spelling_idxs, word_idx, score)
```
in [fairseq/examples/speech_recognition/new/decoders/flashlight_decoder.py](https://github.com/facebookresearch/fairseq/blob/main/examples/speech_recognition/new/decoders/flashlight_decoder.py)
And the transcription worked but it did not gave satisfactory transcription.
Therefore, the problem lies in lexicon file only.

**Comment by Jiya126** [comment]
Summary of approaches so far:
1. Trained kenLM model for english using given [colab file](https://colab.research.google.com/drive/102yFuOZkzQoCr4VpVaD7Te-cUgW0Zmwf?usp=sharing). Refer [this](https://github.com/Samagra-Development/ai-tools/issues/211#issuecomment-1656054696) for more. 
The integration gave assertion errors there as well, confirming the errors within LM model files or parameters used for integrating the models.
2. The assertion error comes from [flashlight_decoder.py](https://github.com/facebookresearch/fairseq/blob/main/examples/speech_recognition/new/decoders/flashlight_decoder.py). So, after commenting out that error, the output wasn't satisfactory. Therefore, eliminating this solution. 
The error arises due to <unk> token there, that suggests error with lexicon and bin file, i.e. error in creating kenLM files.
Will be analyzing the flashlight_decoder.py file to get more insights into the error and the <unk> token being used
