### ISSUE TITLE
Repo Restructuring

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#83]
- [x] Dockerfile for evey model
- [ ] Import Hugginface Transformers through repository_data.json
	- [ ] Download should be on Volumes when deployment
	- [ ] Optimize for cold starts
	- [x] Dynamic based on repository_data.json - Design
		- [ ] Show progress

**Comment by GautamR-Samagra** [comment]
@ChakshuGautam I will not be able to work on this till Friday. Is there anyone else? 
 Its to re-write the api.py files inside each model. Should take around 0.5 to 1 hour per model. There are around 10 models.

**Comment by Sarthakrw** [comment]
Hey @ChakshuGautam,

Can I work on this issue? I'm available and interested in rewriting the api.py files for each model.

Please let me know if I can proceed with this. Thank you!

**Comment by ChakshuGautam** [comment]
@Sarthakrw assigned this to you.

**Comment by Sarthakrw** [comment]
I have a few questions,

1. Do you want me to create a pyproject.toml for each individual model first then the docker file for each ? Also some of the models only contain readme files (intent_recognition, text_transliteration, text2speech etc) so how am I supposed to find the dependencies for those models ?
2. For importing Huggingface Transformers can you give more detail on how I can extract the necessary details from the repository_data.json file to correctly import the Huggingface Transformers modules or components for each model? Also as I said previously Some of the models only contain readme files so where would I import the modules to ?
3. And to solve the volume part can u state which of the files or resources need to be downloaded during deployment.

I apologise if these queries are rudimentary,  i'm new to open source and this will be my first contribution.

**Comment by GautamR-Samagra** [comment]
- You need not do anything for the folders are empty (only readme files) 
- We can start with simply creating the api.py files for the identified folders. You can either create a pyproject.toml file (if you plan to use poetry) or requirements.txt if you want to use pip. 
- On getting the Huggingface Transformers, I think the decision is not made yet. @singhalkarun  can update when the flow for that decided.  
- Some models are simply calling api calls, others are actually downloading models (e.g. [translation](https://github.com/Samagra-Development/ai-tools/tree/restructure/src/text_translation/ai4bharat) ). Only for these, they need to be downloaded into volumes instead of clogging up root space.

**Comment by ChakshuGautam** [comment]
1. Yes. You can find the dependencies inside the deploy.sh for those models.
2. You can define new fields that would help you do this. The spec is evolving right now so all power to you on that front.
3. None of the files will be downloaded during deployment. They will be downloaded when the service is starting up. Hugginface automatically downloads and initiates the models but this happen in the default folder - this needs to be in a volume so that it doesn't fill the OS Disk.
